[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "munch-group"]
name = "bioinformatics"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cryptography = ">=46.0.2,<47"
jupyter = ">=1.1.1,<2"
pbkdf2 = ">=1.3,<2"
pycryptodome = ">=3.23.0,<4"
cloudpickle = ">=3.1.1,<4"
colorama = ">=0.4.6,<0.5"
conda = ">=25.7.0,<26"
git = ">=2.51.0,<3"
jupyterlab = ">=4.4.9,<5"
pandoc = ">=3.6.3,<4"
patool = ">=4.0.1,<5"
plotly = ">=6.3.0,<7"
pynput = ">=1.8.1,<2"
pypdf2 = ">=3.0.1,<4"
pyyaml = ">=6.0.3,<7"
rich = ">=14.1.0,<15"
scipy = ">=1.16.2,<2"
seaborn = ">=0.13.2,<0.14"
tabulate = ">=0.9.0,<0.10"
textual = ">=6.2.0,<7"
typing_extensions = ">=4.15.0,<5"
openpyxl = ">=3.1.5,<4"
quarto = ">=1.8.25,<2"
xlsxwriter = ">=3.2.6,<4"
