[workspace]
authors = ["Kasper Munch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge"]
name = "bioinformatics"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cryptography = ">=45.0.6,<46"
jupyter = ">=1.1.1,<2"
pbkdf2 = ">=1.3,<2"
pycryptodome = ">=3.10"
ascii-art = ">=6.5,<7"
cloudpickle = ">=3.1.1,<4"
colorama = ">=0.4.6,<0.5"
conda-build = ">=25.7.0,<26"
git = ">=2.49.0,<3"
jupyterlab = ">=4.4.5,<5"
pandoc = ">=3.7.0.2,<4"
pandoc-crossref = ">=0.3.20,<0.4"
patool = ">=4.0.1,<5"
plotly = ">=6.3.0,<7"
pynput = ">=1.8.1,<2"
pypdf2 = ">=3.0.1,<4"
pyyaml = ">=6.0.2,<7"
rich = ">=14.1.0,<15"
scipy = ">=1.16.1,<2"
seaborn = ">=0.13.2,<0.14"
tabulate = ">=0.9.0,<0.10"
textual = ">=5.3.0,<6"
typing_extensions = "4.4.0.*"
openpyxl = ">=3.1.5,<4"
xlsxwriter = ">=3.2.5,<4"
