project:
  type: book
  output-dir: _book/draft
  # post-render: 
  #   - quarto render --to html --profile ta  

book:
  title: "Bioinformatics and Programming"
  # title: "<br>"
  subtitle: "AU course: Bioinformatik og programmering - 2024"
  # description: 'A course in bioinformatics and programming'
  # author: "Kasper Munch"
  sidebar:
    title: "Content"
    collapse-level: 1
    background: "white"      
  chapters:
    - index.qmd
    - curriculum.qmd
    # - part: "Schedule"
    #   chapters:
    #   - overview.qmd
    #   - weekplan.qmd
    - weekplan.qmd
    - part: "Learning Python"
      chapters:
      - chapters/python/preface.qmd
      - chapters/python/before_you_begin.qmd
      - chapters/python/writing_a_program.qmd
      - chapters/python/dealing_with_values.qmd
      - chapters/python/the_order_of_events.qmd
      - chapters/python/course_tools.qmd
      - chapters/python/controlling_behavior.qmd
      - chapters/python/organizing_your_code.qmd
      - chapters/python/python_values_are_objects.qmd
      - chapters/python/lists.qmd
      - chapters/python/dictionaries.qmd
      - chapters/python/gluing_values_in_sequence.qmd
      - chapters/python/iteration_over_values.qmd
      - chapters/python/working_with_data_files.qmd
      - chapters/python/data_structures.qmd
      - chapters/python/unleash_your_functions.qmd
      - chapters/python/testing_your_code.qmd
      - chapters/python/your_own_types_of_objects.qmd
      - chapters/python/using_code_from_other_files.qmd
      - chapters/python/on_the_shoulders_of_giants.qmd
      - chapters/python/appendix_pymol.qmd
    - part: "Bioinformatics"
      chapters: 

      # I should still do lectures one week and exercises/project next

      # NB: they learn python for bioinformatics, so they should be able to use it for the bioinformatics part of the course ...!
      # If possible, the python and web projects should be connected (the project could be downstream of a web finding)

      # NB: for each topic introduce a case and problem to solve, do theory and have them solve problem with web and project
      - chapters/bioinformatics/preface.qmd

      # finding information
      # problem: GWAS candidates
      - chapters/bioinformatics/gwas.qmd # serves only as extended exercise introduction
      - chapters/bioinformatics/databases.qmd
      - chapters/web/gwas_databases/index.qmd # W
      - chapters/project/translation_project/index.qmd # P

      # HMM
      # problem: finding genes
      - chapters/bioinformatics/hidden_markov_models.qmd
      - chapters/bioinformatics/sequence_annnotation.qmd
      - chapters/web/new_hmm_exercise/index.qmd # web exercise using hmm # W
      - chapters/project/orf_project/index.qmd # P

      # NN
      # problem: signal peptide?      
      - chapters/bioinformatics/neural_networks.qmd
      - chapters/web/neural_networks/index.qmd # W
      - chapters/project/folding_project/index.qmd # P

      # Assembly
      # problem: long read sequencing of unknown thing
      - chapters/bioinformatics/assembly_and_mapping.qmd # serves only as extended exercise introduction
      - chapters/project/assembly_project/index.qmd # P

      # alignment
      # problem: ccr5     
      - chapters/bioinformatics/global_alignment.qmd
      - chapters/bioinformatics/local_alignment.qmd
      - chapters/project/alignment_project/index.qmd # P
      - chapters/web/ccr5_pwalign/index.qmd # W

      # sub matrices / blast (with expanded blossum)
      # problem: MRSA     
      - chapters/bioinformatics/protein_substitution_matrices.qmd
      - chapters/bioinformatics/database_searching.qmd
      - chapters/web/mrsa_blast_multalign/index.qmd # W
      - chapters/project/hiv_project/index.qmd # P (maybe modified to use local alignmnet)

      # sequence clustering
      - chapters/bioinformatics/multiple_alignment.qmd # serves only as extended exercise introduction
      - chapters/bioinformatics/clustering.qmd      
      - chapters/project/seqdist_project/index.qmd # P

      # phylogentics
      - chapters/bioinformatics/models_of_dna_evolution.qmd
      - chapters/bioinformatics/phylogenetics.qmd
      - chapters/web/aardwark_seqdist/index.qmd # W








      - chapters/web/orf_finding.qmd # W
#      - chapters/web/long_reads.qmd # W
    - part: "Supplementary"
      chapters: 
      - supplementary/project_files.qmd
      - supplementary/recordings2024.qmd
      - supplementary/slides2024.qmd
      - supplementary/bioinformatics_resources.qmd
    - assignments.qmd
    - exam.qmd
  # downloads: [pdf]

bibliography: references.bib

crossref:
  sec-prefix: "exercise"
  
# embed-resources: true

format:
  html:
    # mainfont: "Passata"
    theme: 
      - default
      - custom.scss
    highlight-style: kate 
    fig-width: 5
    fig-height: 3
    filters: 
      - quarto
      - headers.lua
    notebook-links: global
    # number-sections: false
    number-sections: true      
    code-block-bg: "#f9f9f9"
    # code-tools: true    
  # pdf:
  #   documentclass: scrbook
  #   papersize: a4
  #   highlight-style: kate 
  #   fig-width: 7
  #   fig-height: 5
  #   toc-depth: 2
  #   secPrefix:
  #     - "exercise"
  #     - "exercises"
  #   include-in-header:
  #     - file: header_extra.tex
  # # epub:
  # #   cover-image: cover.png
  # #   highlight-style: kate 
  # #   # epub-fonts: DejaVuSans-*.ttf